services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: terminlock
      POSTGRES_PASSWORD: terminpass
      POSTGRES_DB: terminlock
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U terminlock -d terminlock"]
      interval: 3s
      timeout: 3s
      retries: 20

  cache:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
